#! /bin/sh

sxhkd &
~/.config/polybar/launch.sh &
compton --config ~/.compton.conf &
wal -R -t --vte &

bspc monitor HDMI-0 -d     
bspc monitor DVI-I-1 -d      

bspc config border_width         0
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius        10

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
