#! /bin/sh

sxhkd &
compton --config ~/.compton.conf &
wal -R -t --vte &
~/.config/polybar/launch.sh &

bspc monitor DisplayPort-0 -d     
bspc monitor HDMI-A-0 -d      

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
